import { Vehicle, ServiceLogEntry, FuelLogEntry, ChargingLogEntry } from "@/types/models";
import { formatDate, formatKm, formatMoney } from "@/utils/format";
import { getVehicleOwnershipCost } from "./ownershipCost";
import { getAllExpenses } from "./fleetAnalytics";
import { todayIso } from "@/utils/date";

/**
 * Plain-text vehicle history report, suitable for sharing (e.g. with a
 * prospective buyer) via the OS share sheet. Deliberately text, not PDF —
 * no PDF/print library is wired into this project yet; this is the
 * "clean shareable view first" fallback rather than adding a dependency
 * for one feature. Vehicle photos aren't included (text-only channel).
 */
export function buildVehicleReportText(
  vehicle: Vehicle,
  serviceEntries: ServiceLogEntry[],
  fuelEntries: FuelLogEntry[],
  chargingEntries: ChargingLogEntry[],
  currencyCode: string
): string {
  const expenses = getAllExpenses(
    [vehicle],
    { [vehicle.id]: fuelEntries },
    { [vehicle.id]: serviceEntries },
    { [vehicle.id]: chargingEntries }
  );
  const cost = getVehicleOwnershipCost(vehicle, expenses);

  const lines: string[] = [];
  lines.push(`VEHICLE HISTORY REPORT`);
  lines.push(`${vehicle.year} ${vehicle.make} ${vehicle.model} — "${vehicle.name}"`);
  lines.push("");
  lines.push(`Plate: ${vehicle.plateNumber || "—"}`);
  lines.push(`VIN: ${vehicle.vin || "—"}`);
  lines.push(`Color: ${vehicle.color || "—"}`);
  lines.push(`Current odometer: ${formatKm(vehicle.currentOdometerKm)}`);
  lines.push("");
  lines.push(`OWNERSHIP`);
  lines.push(`Purchased: ${formatDate(vehicle.purchaseDate)} — ${formatMoney(vehicle.purchasePrice, currencyCode)}`);
  lines.push(`Registration expiry: ${formatDate(vehicle.registrationExpiry)}`);
  lines.push(`Insurance expiry: ${formatDate(vehicle.insuranceExpiry)}`);

  if (serviceEntries.length > 0) {
    lines.push("");
    lines.push(`SERVICE HISTORY (${serviceEntries.length} record${serviceEntries.length === 1 ? "" : "s"})`);
    const sorted = [...serviceEntries].sort((a, b) => a.date.localeCompare(b.date));
    for (const e of sorted) {
      const shop = e.shop ? ` — ${e.shop}` : "";
      lines.push(`${formatDate(e.date)} · ${formatKm(e.odometerKm)} — ${e.type} — ${formatMoney(e.cost, currencyCode)}${shop}`);
      if (e.notes) lines.push(`  Notes: ${e.notes}`);
    }
  }

  lines.push("");
  lines.push(`SPENDING SUMMARY`);
  lines.push(`Fuel: ${formatMoney(cost.fuelTotal, currencyCode)}`);
  if (cost.chargingTotal > 0) lines.push(`Charging: ${formatMoney(cost.chargingTotal, currencyCode)}`);
  lines.push(`Maintenance & repairs: ${formatMoney(cost.serviceTotal, currencyCode)}`);
  lines.push(`Total logged running costs: ${formatMoney(cost.runningTotal, currencyCode)}`);
  lines.push(`Estimated total cost of ownership: ${formatMoney(cost.totalCostOfOwnership, currencyCode)}`);
  lines.push("");
  lines.push(`Generated by Garahe on ${formatDate(todayIso())}`);

  return lines.join("\n");
}
